name: pygbag_build
on: [ workflow_dispatch ]


jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          python -m pip install git+https://github.com/pygame-web/pygbag.git
          python -m pygbag --git --ume_block=0 --build $GITHUB_WORKSPACE/main.py
      - name: "Upload to GitHub pages branch gh-pages"
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build/web
